name: Build containers

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  AZURE_CLI_VERSION: "2.37.0"
  PYTEST_ARGS: "-n 8 --disable-warnings --durations 10"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - registry.access.redhat.com/ubi8/ubi:latest
          - quay.io/centos/centos:stream9
          - registry.fedoraproject.org/fedora:35
          - registry.fedoraproject.org/fedora:36
          - registry.fedoraproject.org/fedora:rawhide
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install requirements
        run: |
          echo "fastestmirror=1" >> /etc/dnf/dnf.conf
          echo "max_parallel_downloads=20" >> /etc/dnf/dnf.conf
          dnf -qy upgrade
          dnf -qy install python3
          curl -sL https://bootstrap.pypa.io/get-pip.py | python3
          pip -q install virtualenv
          virtualenv azure-cli-venv
          azure-cli-venv/bin/pip install -U pip pytest pytest-xdist wheel

      - name: Download azure-cli
        run: |
           curl -sLo azure-cli.tgz https://github.com/Azure/azure-cli/archive/refs/tags/azure-cli-${AZURE_CLI_VERSION}.tar.gz
           mkdir azure-cli
           tar xf azure-cli.tgz --strip-components=1 -C azure-cli

      - name: Install requirements
        run: |
          azure-cli-venv/bin/pip install \
            -r azure-cli/src/azure-cli/requirements.py3.Linux.txt \
            azure-cli/src/azure-cli*/

      - name: Test azure-cli-core
        if: always()
        run: |
          azure-cli-venv/bin/pytest $PYTEST_ARGS azure-cli/src/azure-cli-core \
            -k "not test_get_mgmt_service_client and not test_help_loads"

      - name: Test azure-cli-telemetry
        if: always()
        run: azure-cli-venv/bin/pytest $PYTEST_ARGS azure-cli/src/azure-cli-telemetry

      - name: Test azure-cli command modules
        if: always()
        run: |
          BASE_DIR=$(pwd)
          pushd azure-cli/src/azure-cli/azure/cli/command_modules/
            TEST_DIRECTORIES=$(find . -name latest -type d -printf " %p")
            ${BASE_DIR}/azure-cli-venv/bin/pytest $PYTEST_ARGS $TEST_DIRECTORIES
          popd
