name: Build containers

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  AZURE_CLI_VERSION: "2.37.0"
  AZURE_TEST_RUN_LIVE: "False"
  PYTEST_ARGS: "-n 8 --disable-warnings --durations 10 --vcr-record=none"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - quay.io/centos/centos:stream9
          # - registry.fedoraproject.org/fedora:35
          # - registry.fedoraproject.org/fedora:36
          - registry.fedoraproject.org/fedora:rawhide
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install requirements
        run: |
          echo "fastestmirror=1" >> /etc/dnf/dnf.conf
          echo "max_parallel_downloads=20" >> /etc/dnf/dnf.conf
          dnf -qy upgrade
          dnf -qy install python3
          curl -sL https://bootstrap.pypa.io/get-pip.py | python3
          pip -q install virtualenv
          virtualenv azure-cli-venv
          azure-cli-venv/bin/pip install -U pip pytest pytest-xdist pytest-vcr wheel

      - name: Download azure-cli
        run: |
           curl -sLo azure-cli.tgz https://github.com/Azure/azure-cli/archive/refs/tags/azure-cli-${AZURE_CLI_VERSION}.tar.gz
           mkdir azure-cli
           tar xf azure-cli.tgz --strip-components=1 -C azure-cli

      - name: Install requirements
        run: |
          azure-cli-venv/bin/pip install azure-cli/src/azure-cli-telemetry --no-deps
          azure-cli-venv/bin/pip install azure-cli/src/azure-cli-core --no-deps
          azure-cli-venv/bin/pip install azure-cli/src/azure-cli --no-deps
          azure-cli-venv/bin/pip install azure-cli/src/azure-cli-testsdk --no-deps
          azure-cli-venv/bin/pip -r azure-cli/src/azure-cli/requirements.py3.Linux.txt

      - name: Run serial tests
        if: always()
        run: |
          azure-cli-venv/bin/python -m pytest \
            -v --boxed -p no:warnings --log-level=WARN --durations=10 \
            azure-cli/src/azure-cli/azure/cli/command_modules/network/tests/latest \
            azure-cli/src/azure-cli/azure/cli/command_modules/appservice/tests/latest \
            azure-cli/src/azure-cli-core/azure/cli/core/tests \
            azure-cli/src/azure-cli/azure/cli/command_modules/botservice/tests/latest \
            azure-cli/src/azure-cli/azure/cli/command_modules/cloud/tests/latest \
            azure-cli/src/azure-cli-telemetry/azure/cli/telemetry/tests
