name: Build containers

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    strategy:
      matrix:
        container:
          - registry.fedoraproject.org:rawhide
          - registry.fedoraproject.org:rawhide
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test container
        run: cat /etc/fedora-release
