name: Test Python

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  AZURE_TEST_RUN_LIVE: "False"
  PYTEST_ARGS: "-n 8 --disable-warnings --durations 10 --vcr-record=none"

jobs:
  test_python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11-dev']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone azure-cli repository
        uses: actions/checkout@v3
        with:
          repository: azure/azure-cli
          ref: azure-cli-2.37.0
          path: azure-cli

      - name: Install requirements
        run: |
          pip install -U pip setuptools wheel
          pip install -U azdev

      - name: Setup azdev
        run: azdev setup -c
        working-directory: azure-cli

      - name: Run serial
        run: azdev test --no-exitfirst --verbose --pytest-args "--durations=10"
        working-directory: azure-cli